const Joi = require('joi');

exports.wishList = {
    cars: [
        'name',
        'model',
        'class_name',
        'number',
        'mileage',
        'carcass_condition',
        'release_date',
        'fuel_level',
        'osago_number',
        'osago_expiration_date',
        'maintenance',
        'market_price',
        'purchase_price',
        'payment_amount',
        'payment_date',
        'in_leasing',
        'leasing_expiration_date',
    ],
    customers: Joi.object({
        'birthday': Joi.date().iso(),
        'driver_license_issue_date': Joi.date().iso(),
        'driver_license_expiration_date': Joi.date().iso(),
        'driver_license': Joi.string().trim(),
        'passport_issue_date': Joi.date().iso(),
        'passport_issued_by': Joi.string().trim(),
        'passport_division_code': Joi.string().trim(),
        'location': Joi.string().trim(),
        'is_legal_entity': Joi.number().valid([0, 1]),
        'legal_address': Joi.string().trim(),
        'actual_address': Joi.string().trim(),
        'email': Joi.string().trim(),
        'ogrn': Joi.string().trim(),
        'bank_name': Joi.string().trim(),
        'r_account': Joi.string().trim(),
        'k_account': Joi.string().trim(),
        'bik': Joi.string().trim(),
        'inn': Joi.string().trim(),
        'name': Joi.string().trim(),
        'passport': Joi.string().trim(),
        'contact_number': Joi.string().trim(),
        'discount': Joi.number(),
    }).when(Joi.object({
        is_legal_entity: Joi.number().valid(1)
    }).unknown(), {
            then: Joi.object().with('is_legal_entity', [
                'legal_address',
                'actual_address',
                'email',
                'ogrn',
                'inn',
                'bank_name',
                'r_account',
                'k_account',
                'bik',
                'inn',
            ]),
            otherwise: Joi.object().with('is_legal_entity', [
                'birthday',
                'driver_license_issue_date',
                'driver_license_expiration_date',
                'driver_license',
                'passport_issue_date',
                'passport_issued_by',
                'passport_division_code',
                'location',
            ])
        }),
    passengers: [
        'name',
        'birthday',
        'contact_number'
    ],
    drivers: [
        'name',
        'birthday',
        'contact_number',
        'car_id',
        'driver_license',
        'license_date_issue',
        'license_date_expiration',
        'passport',
        'passport_date_issue',
        'passport_issued_by',
        'passport_division_code',
        'passport_location',
        'is_individual',
    ],
    itineraries: [
        'name',
        'price',
    ],
    cashStorages: [
        'cashbox',
        'name',
        'number',
    ],
    additionalServices: [
        'name',
        'price',
    ],
    apartments: [
        'address',
        'rooms',
        'price_per_day',
        'utilities_per_month',
    ],
    apartmentReservations: [
        'apartment_id',
        'customer_id',
        'passenger_id',
        'prepayment',
        'cash_storage_id',
        'services',
        'discount',
        'number_days',
        'price_per_day',
        'contact_number',
        'comment',
        'sum',
        'entry',
        'status',
        'departure',
    ],
    carsPrice: [
        'name',
        'model',
        'class_name',
        'price_per_day',
        'pledge',
        'limit_per_day',
        'surcharge',
    ],
    carReservation: [
        'customer_id',
        'contact_number',
        'passenger_id',
        'driver_id',
        'car_id',
        'price_id',
        'class_name',
        'itinerarie_id',
        'cash_storage_id',
        'services',
        'prepayment',
        'comment',
        'sum',
        'status',
    ],
    costsCategories: Joi.object({
        id: Joi.number(),
        title: Joi.string().trim()
    })
};